package com.example.projectmanagement.dto;

import com.example.projectmanagement.model.User;
import jakarta.validation.constraints.*;
import lombok.Data;

@Data
public class UserDto {

    public interface StudentValidation {}
    public interface SupervisorValidation {}

    private Long id;  // Optional for new users (generated by DB)

    @NotNull(message = "Name is required")
    private String name;

    @Email(message = "Email should be valid")
    @NotNull(message = "Email is required")
    private String email;

   // @NotNull(message = "Role is required") spring boot backend keep role on its own
    private String role;

    @NotNull(message = "Password is required")
    private String password;

    @NotBlank(message = "Program is Required", groups = StudentValidation.class)
    private String program;

    @NotBlank(message = "Project title is required", groups = StudentValidation.class)
    private String projectTitle;


}
